makeCacheMatrix <- function(x,y)
{         
        set<- function()
        { 
           x = matrix(x,nrow=y,ncol=y)
           x        
 }
         i<<- 1
        
   
         
}
cacheSolve <- function(x,y,...)
{
       x = set() 
       jai = list()
       inverse = list()
      if (i == 1)
 {       
         jai[[i]]= x
         i=i+1
         inverse[[i]] = solve(x)
         return(solve(x))
  }
        j=1
  for( j in i)
{     
      
